[package]
name = "config-check"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
config = "0.13.3"
propparse = "0.2.2"
serde = { version = "1.0.154", features = ["derive"] }
